apiVersion: v1
kind: Pod
metadata:
  name: portfolio-pod
  labels:
    app: portfolio
spec:
  containers:
    - name: web
      image: saadali96/portfolio:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8000
      envFrom:
        - secretRef:
            name: portfolio-secrets